// <auto-generated />
namespace vk2tg.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class userHasBlocked : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userHasBlocked));
        
        string IMigrationMetadata.Id
        {
            get { return "201706151749054_userHasBlocked"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
